# -*- mode: ruby -*-
# vi: set ft=ruby :

# This vagrantfile creates a VM with the development environment
# configured and ready to go.
#
# The setup script (env var $script) in this file installs docker.
# This is not in the setup.sh file because the docker install needs
# to be secure when running on a real linux machine.
# The docker environment that is installed by this script is not secure,
# it depends on the host being secure.
#
# At the end of the setup script in this file, a call is made
# to run setup.sh to create the developer environment.

# This is the mount point for the sync_folders of the source
SCRIPTS_DIR = "/scripts"

$base_script = <<SCRIPT
set -x

cd #{SCRIPTS_DIR}
chmod +x *.sh

./install_basic.sh
./install_docker-ce_ubuntu.sh

SCRIPT

$rancher_script = <<SCRIPT
set -x

#cd #{SCRIPTS_DIR}
#./init_rancher.sh

SCRIPT

#baseimage_release = File.read '../.baseimage-release'

Vagrant.require_version ">= 2.0.0"
Vagrant.configure('2') do |config|
  
  config.vm.boot_timeout = 1000

  config.vm.synced_folder "./scripts", "#{SCRIPTS_DIR}"

  config.vm.define "base", primary: true do |base|
    #base.vm.box = "box-cutter/ubuntu1604"
    base.vm.box = "velocity42/xenial64"
    #
    base.vm.provision :shell, inline: $base_script

    base.ssh.username = "vagrant"
    #base.ssh.password = "vagrant"

    base.vm.provider :virtualbox do |vb|
      vb.name = "base"
    end
  end
  
  config.vm.define "master", primary: true do |master|
    master.vm.box = "alphacar/rancher_base"

    #master.vm.provision "shell",
    #run: "always",
    #inline: "route add default gw 192.168.10.1 eth1"

    master.vm.network "public_network"#, bridge: "rancher_net", ip: "192.168.101.250"

    master.vm.network :forwarded_port, guest: 18080, host: 18080
    master.vm.network :forwarded_port, guest: 18443, host: 18443

    master.ssh.username = "vagrant"
    master.ssh.private_key_path = "./.vagrant/machines/base/virtualbox/private_key"
    #master.ssh.password = "vagrant"

    master.vm.provider :virtualbox do |vb|
      vb.name = "master"
      vb.customize ['modifyvm', :id, '--memory', '4096']
      vb.cpus = 2
    end

    master.vm.provision :shell, inline: $rancher_script
  end

  config.vm.define "worker", primary: true do |worker|
    worker.vm.box = "alphacar/rancher_base"

    worker.vm.network "public_network"#, bridge: "rancher_net", ip: "192.168.101.251"

    worker.ssh.username = "vagrant"
    worker.ssh.private_key_path = "./.vagrant/machines/base/virtualbox/private_key"
    #worker.ssh.password = "vagrant"

    worker.vm.provider :virtualbox do |vb|
      vb.name = "worker"
      vb.customize ['modifyvm', :id, '--memory', '2048']
      vb.cpus = 2
    end
    
  end

  config.vm.define "node3", primary: true do |node3|
    node3.vm.box = "alphacar/rancher_base"

    node3.vm.network "public_network"#, bridge: "rancher_net", ip: "192.168.101.251"

    node3.ssh.username = "vagrant"
    node3.ssh.private_key_path = "./.vagrant/machines/base/virtualbox/private_key"
    #worker.ssh.password = "vagrant"

    node3.vm.provider :virtualbox do |vb|
      vb.name = "node3"
      vb.customize ['modifyvm', :id, '--memory', '3072']
      vb.cpus = 2
    end
    
  end

end
